version: '3'

services:
  nginx:
    image: nginx:1.15-alpine
    container_name: nginx_docker
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./data/nginx/:/etc/nginx/conf.d
      - ./data/sites-enabled:/etc/nginx/sites-enabled
      - "443:443"
  privatebin:
    container_name: privatebin_docker
    image: privatebin/nginx-fpm-alpine:1.3.1
    depends_on:
      - nginx
    ports:
      - "8080"
    restart: unless-stopped
    volumes:
      - ./data/privatebin:/srv/data
